import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins, League_Spartan } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800', '900'], 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const leagueSpartan = League_Spartan({ 
  subsets: ['latin'],
  variable: '--font-league-spartan',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} ${leagueSpartan.variable} font-sans h-full antialiased`}
    >
<body className={`min-h-full flex flex-col ${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
